steps:
- name: 'gcr.io/$PROJECT_ID/scala-sbt'
  timeout: 800s
  args: ['clean', 'docker:publishLocal']
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'jenkins-mqtt:1.0', 'eu.gcr.io/$PROJECT_ID/jenkins-mqtt:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/jenkins-mqtt:$COMMIT_SHA']
