apiVersion: v1
kind: Service
metadata:
  name: jenkins-mqtt
spec:
  type: NodePort
  selector:
    app: jenkins-mqtt
  ports:
  - port: 9000
    name: jenkins-mqtt
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-mqtt
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins-mqtt
    spec:
      containers:
      - name: jenkins-mqtt
        image: localhost:5000/jenkins-mqtt:1.0
        ports:
        - containerPort: 9000
